import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

const { width } = Dimensions.get('window'); 

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: '#F5F7F8', flexDirection: 'row' },
  leftcontainer:{ flex: 1, flexDirection: 'column', },
  rightcontainer:{ flexDirection: 'column', minWidth: 340, width: 340, paddingTop: 10, },
  ordersum:{ width: 50, height: 60, borderRadius: 4, marginRight: 0, },
  orderName: { flexDirection: 'column', fontSize: 11, width: 65, },
  headerContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 4, marginRight: 10, },
  logo: { width: 100, height: 100, resizeMode: 'contain', marginRight: 20, },
  titleSearchContainer: { flex: 1, justifyContent: 'center', },
  pageTitle: { fontSize: 26, color: '#203B36', fontWeight: 'bold', marginBottom: 14, marginTop: 20, fontFamily: 'Poppins-Black', },
  searchBarContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, borderColor: '#DDB04B', width: '100%', borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, backgroundColor: '#fff', shadowColor: '#203B36', elevation: 8, },
  searchIcon: { marginRight: 8, },
  searchBar: { flex: 1, height: 40, color: '#DDB04B', },
  categoryContainer: { paddingVertical: 10, },
  categoryButton: { marginHorizontal: 8, paddingVertical: 10, paddingHorizontal: 16, backgroundColor: '#DDB04B', height: 40, width: 100, borderRadius: 5, justifyContent: 'center', alignItems: 'center', marginRight: 40, shadowColor: '#DDB04B', elevation: 8, },
  categoryButtonText: { fontSize: 16, fontWeight: 'bold', color: '#0A1D1A', fontFamily: 'Poppins-Regular' },
  mainContent: { flexDirection: 'row', flex: 30, height: '100%', },
  productsContainer: { paddingBottom: 4, },
  productsFlatList: { flex: 1, },
  row: { justifyContent: 'space-between', },
  product: { flex: 1, margin: 14, backgroundColor: '#fff', borderRadius: 16, padding: 20, height: width * 0.50, shadowColor: '#203B36', elevation: 8, alignItems: 'center' },
  productImage: { width: '100%', height: '30%', borderRadius: 8, marginBottom: 5, },
  productName: { fontSize: 20,marginBottom: 2,margin: 10,fontWeight: 'bold',color: '#DDB04B',textAlign: 'left',fontFamily: 'Poppins-Regular'},
  productCategory: { fontSize: 14, color: '#122D28', marginBottom: 8, },
  stockStatus: { fontSize: 14, marginBottom: 4, },
  inStock: {
    color: 'green',
  },
  outOfStock: {
    color: 'red',
  },
  disabledButton: {
    backgroundColor: '#888',
  },
  priceContainer: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    margin: 10,
  },
  priceWrapper: {
    alignItems: 'center',
    margin: 4,
  },
  priceButton: {
    width: '100%',
    backgroundColor: '#DDB04B',
    padding: 8,
    borderRadius: 5,
    flexDirection: 'column',
    alignItems: 'center',
  },
  productPrice: {
    color: '#122D28',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 0,
    fontFamily: 'Poppins-Regular'
  },
  cupIcon: {
    marginRight: 0,
  },
  sizeLabel: {
    marginTop: 4,
    fontSize: 12,
    color: '#203B36',
    fontFamily: 'Poppins-Regular'
  },
  variationTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#DDB04B',
    marginBottom: -2,
    marginTop: -5,
    margin: 10,
    width: '100%',
    fontFamily: 'Poppins-Regular',
    alignItems: 'center',
  },
  orderSummaryContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    width: '100%', 
    maxWidth: 340, 
    shadowColor: '#203B36',
    elevation: 10,
    margin: 10, 
    alignSelf: 'center',
    height: '100%',
  },
  orderSummary:{
    flex: 1
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 12,
    marginHorizontal: 12,
  },
  orderNumber: {
    color: '#DDB04B',
    fontSize: 18,
    fontFamily: 'Poppins-Bold',
    marginHorizontal: 10,
  },
  clearAll: {
    color: '#FF0000',
    fontFamily: 'Poppins-Bold',
    marginHorizontal: 10,
  },
  customerNameInput: {
    backgroundColor: '#fff',
    color: '#DDB04B',
    borderRadius: 5,
    padding: 10,
    fontFamily: 'Poppins-Regular',
    shadowColor: '#203B36',
    elevation: 10,
    marginHorizontal: 12,
    marginTop: 15,
  },
  productList: {
    marginBottom: -10,
    marginHorizontal: 12,
    width: '100%',
    fontSize: 8,
    height: 80,
    minHeight: 60,
    overflow: 'hidden',
  },
  productItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
    marginHorizontal: 8,
    fontWeight: '800',
    fontFamily: 'Poppins-ExtraBold',
  },
  summaryDetails: {
    marginBottom: 10,
    fontFamily: 'Poppins-Regular',
    justifyContent: 'space-between',
    marginHorizontal: 12,
    marginTop: 20,
  },
  dineInTakeOut: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginHorizontal: 12,
    marginTop: 10,
  },
  dineOption: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#A9A9A9',
    borderRadius: 5,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  selectedOption: {
    backgroundColor: '#E8B86D',
    borderColor: '#DDB04B',
    borderWidth: 2,
  },
  printButton: {
    backgroundColor: '#203B36',
    borderRadius: 5,
    paddingVertical: 10,
    marginHorizontal: 16,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#203B36',
    elevation: 8,
  },
  printButtonText: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
  },
  picker: {
    width: '100%',
    height: 30,
  },
  pickerWrapper: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    marginVertical: 10,
    height: 55,
    overflow: 'hidden',
  },
  cashier: {
    marginBottom: 8,
    fontSize: 12,
    opacity: 40,
    marginHorizontal: 22,
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginEnd: 12,
  },
  counterButton: {
    backgroundColor: '#006400', 
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    padding: 10,
    borderRadius: 20, 
    marginHorizontal: 10,
    textAlign: 'center',
    minWidth: 40, 
  }
});

export default styles;